"""Level_Grouping I/O shell: persist the serialized LeveledPath for a path.

This module is the thin, best-effort I/O shell paired with the pure decision
core in ``level_grouping.py`` (Phase 1, Req 1 structure). Mirroring the
convention of ``coverage_view_store.py`` / ``spine_router_runner.py`` -- and the
design's "pure decision core, thin I/O shell" principle -- it holds ONLY the
glue that turns an already prerequisite-ordered Spine_Path into a serialized
``LeveledPath`` and persists it; every grouping decision lives in
``level_grouping.group_levels`` and the ordering lives in the existing
``spine_router`` / ``curriculum_spine`` cores. This shell decides nothing and
reimplements no ordering.

The flow (no new LLM call -- the path is already generated by the existing
curriculum/spine machinery, and grouping is a pure partition over it):

1. Take an ordered Spine_Path (a sequence of ``SpineNode`` or any object exposing
   ``topic_slug`` + ``content_level``), or resolve one for a query via the
   existing ``spine_router_runner.resolve_path`` (reuse).
2. Map each node to a :class:`~app.services.level_grouping.PathTopic`
   (``topic_slug`` + ``content_level`` + its 0-based ``position``).
3. Call the pure :func:`~app.services.level_grouping.group_levels`.
4. Serialize the resulting ``LeveledPath`` to a jsonb-ready list
   (``ordinal -> name -> topic_slugs``) and persist it best-effort into the
   nullable ``learning_paths.levels`` column on the existing row.

The ``learning_paths.levels`` column is introduced by the Phase 1 additive
migration (``migration_structured_curriculum_phase1.sql``); this shell is written
to use it and degrades gracefully (logs and returns ``False``) when it is not yet
present, exactly like the other best-effort shells. A NULL / absent
``learning_paths.levels`` renders a single implicit level (legacy behavior), so
persisting the projection is never required for the feed to work.

It is best-effort throughout: every external call is wrapped so a failure
degrades to a safe default and never blocks or crashes the request path.

ASCII only.

Validates: Requirements 1.1, 1.2, 5.3
"""
from __future__ import annotations

import logging
from typing import Iterable

from app.db.supabase import get_client
from app.services.level_grouping import LeveledPath, PathTopic, group_levels

logger = logging.getLogger(__name__)

#: The Supabase table carrying the learner's path and the nullable ``levels``
#: jsonb projection (the column is added by the Phase 1 additive migration).
_LEARNING_PATHS_TABLE = "learning_paths"


# ---------------------------------------------------------------------------
# Pure-ish bridging (no I/O)
# ---------------------------------------------------------------------------

def build_leveled_path(spine_path: Iterable) -> LeveledPath:
    """Group an ordered Spine_Path into a ``LeveledPath`` via the pure core.

    Maps each node in ``spine_path`` -- a sequence of ``SpineNode`` or any object
    exposing ``topic_slug`` and ``content_level`` -- to a
    :class:`~app.services.level_grouping.PathTopic` carrying its 0-based position,
    then defers entirely to :func:`~app.services.level_grouping.group_levels`.
    The input order (the prerequisite order produced by the spine) is preserved;
    this function never reorders. An empty path yields ``LeveledPath(())``.

    Args:
        spine_path: The ordered Spine_Path (``SpineNode`` or equivalent).

    Returns:
        The grouped :class:`LeveledPath`.

    Validates: Requirements 1.1, 1.2
    """
    topics = [
        PathTopic(
            topic_slug=getattr(node, "topic_slug", ""),
            content_level=getattr(node, "content_level", "") or "",
            position=index,
        )
        for index, node in enumerate(spine_path)
    ]
    return group_levels(topics)


def serialize_leveled_path(leveled: LeveledPath) -> list[dict]:
    """Serialize a ``LeveledPath`` to a jsonb-ready list for persistence.

    Each Level becomes an ``{"ordinal", "name", "topic_slugs"}`` object in
    ordinal order; ``topic_slugs`` is a plain list (tuples are not JSON types).
    An empty ``LeveledPath`` serializes to ``[]``. Pure and total.

    Args:
        leveled: The grouped curriculum.

    Returns:
        The jsonb-ready list of level objects.

    Validates: Requirements 1.2, 5.3
    """
    return [
        {
            "ordinal": level.ordinal,
            "name": level.name,
            "topic_slugs": list(level.topic_slugs),
        }
        for level in leveled.levels
    ]


# ---------------------------------------------------------------------------
# Persistence (best-effort; degrades when the column is absent)
# ---------------------------------------------------------------------------

def persist_leveled_path(session_id: str, leveled: LeveledPath, db=None) -> bool:
    """Persist the serialized ``LeveledPath`` into ``learning_paths.levels``.

    Updates the nullable ``levels`` jsonb column on the existing
    ``learning_paths`` row keyed by ``session_id``. Best-effort: any failure
    (including the ``levels`` column not yet existing) is logged and swallowed,
    returning ``False``. A NULL / absent column keeps the legacy single-implicit-
    level rendering, so a failed persist never breaks the feed (Req 5.3).

    Args:
        session_id: The learning path's session id (the row key).
        leveled: The grouped curriculum to serialize and store.
        db: Optional Supabase client (injected in tests); defaults to the shared
            client.

    Returns:
        ``True`` iff the update was issued without error, else ``False``.

    Validates: Requirements 5.3
    """
    if not session_id:
        return False
    if db is None:
        db = get_client()

    payload = serialize_leveled_path(leveled)
    try:
        (
            db.table(_LEARNING_PATHS_TABLE)
            .update({"levels": payload})
            .eq("session_id", session_id)
            .execute()
        )
        logger.info(
            "[leveled_path] persisted %d level(s) for session=%s",
            len(payload),
            session_id,
        )
        return True
    except Exception as exc:
        # The Phase 1 `levels` column may not exist yet (operator-run migration);
        # degrade gracefully -- a NULL column renders a single implicit level.
        logger.warning(
            "[leveled_path] persist levels for session=%s failed "
            "(column may be absent): %s",
            session_id,
            exc,
        )
        return False


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def store_leveled_path_for_query(
    session_id: str, query: str, db=None
) -> LeveledPath:
    """Resolve the Spine_Path for a query, group it, and persist the projection.

    Reuses the existing ``spine_router_runner.resolve_path`` to obtain the
    ordered Spine_Nodes (no ordering is reimplemented here, and grouping itself
    needs no LLM call), maps them through :func:`build_leveled_path`, and persists
    the serialized ``LeveledPath`` into ``learning_paths.levels`` best-effort. Any
    failure resolving the path degrades to an empty path (and thus an empty
    ``LeveledPath`` / single implicit level). Never raises into the request path.

    Args:
        session_id: The learning path's session id (the row key).
        query: The learner query to resolve against the Curriculum_Spine.
        db: Optional Supabase client (injected in tests); defaults to the shared
            client used by the spine reads.

    Returns:
        The grouped :class:`LeveledPath` (also persisted best-effort).

    Validates: Requirements 1.1, 1.2, 5.3
    """
    spine_path: list = []
    try:
        from app.services.spine_router_runner import resolve_path

        result = resolve_path(query, db)
        spine_path = list(result.path)
    except Exception as exc:
        logger.warning(
            "[leveled_path] resolve spine path for session=%s failed: %s",
            session_id,
            exc,
        )

    leveled = build_leveled_path(spine_path)
    persist_leveled_path(session_id, leveled, db)
    return leveled
